import React from 'react'
import './PrivacyAndPolicy.css'

const PrivacyAndPolicy = () => {
    return (
        <>
        <div className='container border border-dark"'>

            <div>
                <h1 className='text-center color' >DUNIYAA PRIVACY AND POLICY</h1>
                <h2 >1. Introduction</h2>
                <p>Welcome to AyConnects PVT LTD operates DUNIYAA	mobile application. Our Privacy Policy helps to explain our data practices, including the information we process to provide our Services. This Privacy Policy sets out how we, AyConnects PVT LTD (“DUNIYAA”), use and protect your personal data that you provide to us, or that is otherwise obtained of generated by us, in connection with your use of our services. For the purpose of this Privacy Policy, <b>‘we’, ‘us’</b>  and <b>‘our’ </b> refers to DUNIYAA, and <b>‘you’, ‘You’, ‘User’ </b> refers to you, the user of the services.</p>
            </div>

            <div className="privacyprinciple">
                <h2 >1.1 Privacy Principles</h2>
                <p>While using our services, you’re trusting us with sharing your information. We accept this big responsibility and promise to work hard to protect your information and put you in control.</p>
                   <p> DUNIYAA has some fundamental principles when it comes to collecting and processing private data:
                </p>
            </div>

            <div className="termsofprivacy">
                <h2 >1.3 Terms of Service</h2>
                <p>While using our services, you’re trusting us with sharing your information. We accept this big responsibility and promise to work hard to protect your information and put you in control.
                    DUNIYAA has some fundamental principles when it comes to collecting and processing private data:
                </p>
            </div>

            <div className="tableofcontents">
                <h2 >1.4 Table of Contents </h2>
                <p>This Privacy Policy ensures and explains the following:</p>
                <ul>
                    <li>Information collection and its use</li>
                    <li>Need for Processing your personal data</li>
                    <li>Security of data</li>
                    <li>Retention of your personal data</li>
                    <li>Transfer of your personal data</li>
                    <li>Data sharing</li>
                    <li>Disclosure of your personal data</li>
                    <li>Children’s privacy</li>
                    <li>Links to other website (ads)</li>
                    <li>Your rights regarding the personal data you provide to us</li>
                    <li>Disclosure text for inclusion in privacy policy</li>
                    <li>Any updates to this privacy policy</li>
                    <li>Contact us</li>
                </ul>
            </div>

            <div className="defination">
                <h2  >2. Definitions</h2>
                <ul>
                    <li>
                        <h5 className='oneline'>	Personal Data: </h5>
                        <p className='oneline'>Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself.</p>
                    </li>
                    <li>
                        <h5 className='oneline'>	Usage Data: </h5>
                        <p className='oneline'>Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself.</p>
                    </li>
                    <li>
                        <h5 className='oneline'>	Cookies: </h5>
                        <p className='oneline'>Cookies are small pieces stored on your device (computer or mobile device).</p>
                    </li>
                    <li>
                        <h5 className='oneline'>	Data Controller: </h5>
                        <p className='oneline'>Data Controller means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.</p>
                    </li>
                    <li>
                        <h5 className='oneline'>	Data Subject: </h5>
                        <p className='oneline'>Data Subject is any living individual who is the subject of Personal Data.</p>
                    </li>
                    <li>
                        <h5 className='oneline'>	User: </h5>
                        <p className='oneline'>The User is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.</p>
                    </li>
                </ul>
            </div>

            <div className="informationcollection">
                <h2 >3. Information collection and its use:</h2>
                <h5 className='oneline'>Purpose :- </h5><p className='oneline'>We collect and process your personal data for:</p>
                <ul>
                    <li>1. Providing effective and innovative services to our users</li>
                    <li>2. To Customize the content you see, to fulfill your requests for certain services</li>
                    <li>3. To detect, Prevent or otherwise address fraud or security issues in respect of our provision of services. </li>
                    <li>4. To contact you about our services via including but not limited to emails, SMS and other modes of communication</li>
                </ul>
            </div>

            <div className="information">
                <h2 >3.1. Information we take from you directly (Personal Data)</h2>
                <p>Personal Information will be kept confidential and will be used for our research, marketing, and strategic client analysis objectives and other internal business purposes only. We do not sell or rent Personal Information except that in case you are a customer of our search services through any of the Media, your Personal Information shall be shared with our subscribers/advertisers and you shall be deemed to have given consent to the same. Further, the users who are listed with us, may call you, based on the query or enquiry that you make with us, enquiring about any</p>
                <ul>
                    <li>	Product / Service or</li>
                    <li>	Product / Service of any subscriber / advertiser or</li>
                    <li>	Product / Service of any particular subscriber / advertiser.</li>
                </ul>
                <p>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. Personally identifiable information may include Full Name, Mobile Number, Email ID, Business Name, Business Address, Business Timings, Business Products, Cookies and Usage data, etc.</p>
                <p>We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe options or instructions provided in any email we send.</p>
            </div>

            <div className="automatically">
                <h2 >3.2 Automatically collected information (Usage Data)</h2>
                <p>We may also collect information how the Service is accessed and used ("Usage Data").
                    This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
                </p>
            </div>

            <div className="usage">
                <h2 >3.2.1 Usage And Log Information. </h2>
                <p>We collect information about your activity on our Services, like service-related,   diagnostic, and performance information. This includes information about your activity (including how you use our Services, your Services settings, how you interact with others using our Services (including when you interact with a business), and the time, frequency, and duration of your activities and interactions), log files, and diagnostic, crash, and performance logs and reports. This also includes information about when you registered to use our Services; the features you use like our messaging, calling, business features; profile photo, "about" information; whether you are online, when you last used our Services (your "last seen"); and when you last updated your "about" information.</p>
            </div>

            <div className="device">
                <h2 >3.2.2 Device And Connection Information</h2>
                <p>	We collect device and connection-specific information when you install, access, or use our Services. This includes information such as hardware model, operating system information, battery level, signal strength, app version, browser information, mobile network, connection information (including phone number, mobile operator or ISP), language and time zone, IP address, device operations information, and identifiers.</p>
            </div>

            <div className="locations">
            <h2 >3.2.3 Location Information</h2>
            <p>	We collect and use precise location information from your device with your permission when you choose to use location-related features, like when you decide to add your business place (while registering your business ), adding public place, when you are in search of any place or any product available at particular place. There are certain settings relating to location-related information which you can find in your device settings or the in-app settings, such as location sharing. Even if you do not use our location-related features, we use IP addresses and other information like phone number area codes to estimate your general location (e.g., city and country). We also use your location information for diagnostics and troubleshooting purposes.</p>
            </div>

            <div className="cookies">
            <h2 >3.2.4 Cookies and other tracking technologies</h2>
            <p>We use cookies and similar tracking technologies to track the activity on our Service and store certain information. Cookies are files with small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. </p>
            <p>You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some parts of our Service.
            Cookies can be ‘Persistent’ or ‘Session’ cookies. Persistent cookies remain on your personal computer or mobile device when you go offline, while session cookies are deleted as soon as you close your web browser or mobile application.
        </p>
            <p>We use both session and persistent cookies for the purposes set out below:</p>
            <ul>
            <li>Necessary / Essential Cookies
            <p>Type: Session Cookies</p>
            <p>Administered by: Us</p>
            <p>Purpose: These cookies are essential to provide you with services available through the website and to enable you to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these cookies, the services that you have asked for cannot be provided, and We only use these cookies to provide you with those services.</p></li>
            <li>Functionality cookies
            <p>Type: Persistent cookies</p>
            
            <p>Administered by: Us</p>
            <p>Purpose: These cookies allow us to remember choices you make when you use the website, such as remembering your login details or language preference. The purpose of these cookies is to provide you with a more personal experience and to avoid you having to re-enter your preferences every time you use the website.</p>
            </li>
            </ul>
            </div>

            <div className="personaldata">
            <h2 >3.3 Use of Your Personal Data</h2>
            <p>We may use personal data for the following purposes:</p>
            <ul>
            <li><b>To provide and maintain our service,</b>	 including to monitor the usage of our service.</li>
            <li> <b>To notify you about the changes to our service:</b> To contact you by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application’s push notifications regarding updates or informative communications related to the functionalities, products or services, including the security updates, when necessary or reasonable for their implementation.</li>
            <li> <b>To allow you </b>to participate in interactive features of our Service when you choose to do so.</li>
            <li> <b>To provide you </b> with news, special offers and general information about other goods, services Xand events which we offer that are similar to those that you have already purchased or Xenquired about unless you have opted not to receive such information</li>
            <li> <b>To provide customer support, </b>to attend and manage your requests to us. </li>
            <li>To gather analysis on valuable information so that we can improve our service.</li>
            <li>To detect, prevent and address technical issues. </li>
            </ul>
            </div>

            <div className="needfor">
            <h2 >4. Need for processing your personal data</h2>
            <p>We use information as we have to operate and provide our service including customer support, improving, fixing and customizing our services. We also use information so that we can understand how people use our services which helps to evaluate and improve our services. We use the information collected in research, develop and to test new services and features and to conduct troubleshooting activities. We also use your information to respond you when you contact us. We use information to verify accounts and activity; to combat harmful conduct, to protect users against bad experiences and scam which helps to promote safety, security and integrity on and off our services (as safety, security and integrity are an integral part of our services.) such as by investigating suspicious activity or violations of our terms and policies and to ensure our services are being used legally. We use information to communicate with you about our services and let you know about our terms, policies and other important updates. We enable you and every users in our service to communicate and interact with each other using our services so that you can browse products and services. </p>
            </div>

            <div className="security">
            <h2 >5. Security of Data:</h2>
            <p>We value your trust in providing us your Personal Information, thus we are striving to use commercially acceptable means of protecting it. But remember that no method of transmission over the internet, or method of electronic storage is 100% secure.</p>
            <p>We take steps to protect your personal information from unauthorized access and against unlawful processing, accidental loss, destruction and damage.</p>
            <p>We will only keep your personal information for as long as we reasonably require and, in any event, only for as long as the Data Protection Legislation allows.</p>
            <p>Where you have chosen a password which, you are responsible for keeping this password confidential. We advise you not to share your password with anyone.</p>
            <p>Unfortunately the transmission of information via the internet is not completely secure and although we will take steps to protect your personal information, we cannot guarantee the security of your personal information transmitted via any transmission is therefore at your own risk.</p>
            </div>

            <div className="retation">
            <h2 >6. Retention Of Your Personal Data</h2>
            <p>The company will retain your personal data only for as long as is necessary for the purposes set out in this privacy policy. We will retain and use your personal data to the extent necessary to comply with our legal obligations e. g. if we are required to retain your data to comply with applicable laws, resolve disputes, and enforce our legal agreements and policies.</p>
            <p>The company will also retain usage data for internal analysis purposes. Usage data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our service, or we are legally obligated to retain this data for longer time periods.</p>
            </div>

            <div className="transfer">
            <h2 >7. Transfer of Your Personal Data</h2>
            <p>Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction.</p>
            <p>Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>
            <p>We will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.</p>
            </div>

            <div className="datasharing">
            <h2 >8. Data Sharing</h2>
            <p>We may share your personal information in the following situations:</p>
            <p><b>8.1 With Service Providers: </b></p>
            <p>We may share your personal information with service providers to monitor and analyze the use of our service, to contact you. We may employ third-party companies and individuals due to the following reasons:</p>
            <ul>
            <li>To facilitate our Service;</li>
            <li>To provide the Service on our behalf;</li>
            <li>To perform Service-related services; or</li>
            <li>To assist us in analyzing how our Service is used.</li>
            </ul>
            <p>We want to inform users of this Service that these third parties have access to your Personal Information. The reason is to perform the tasks assigned to them on our behalf. However, they are obligated not to disclose or use the information for any other purpose.</p>
            <p><b>8.2 For Business Transfers : </b>We may share of transfer your personal information in connection with, or during negotiations of, any merger, sale of company assets, financing, or acquisition of all or a portion of our business to another company.</p>
            <p><b>8.3 With affiliates: </b>We may share your information with our affiliates, in which case we will require those affiliates to honor this privacy policy. Affiliates include our parent company and any other subsidiaries, joint venture partners or other companies that we control or that are under common control with us.</p>
            <p><b>8.4 With Business Partners: </b>We may share your information with our business partners to offer you certain products, services of promotions.</p>
            <p><b>8.5 With Other Users: </b>When you share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside. If you interact with other users or register through a third-party social media service, your contacts on the third-party social media service may see your name, profile, pictures and description of your activity, communicate with you and view your profile.</p>
            </div>

            <div className="disclosure">
            <h2 >9. Disclosure of Your Personal Data</h2>
            <ul>
            <li><b>Business Transactions: </b>If we are involved in a merger, acquisition or asset sale, your Personal Data may be transferred. We will provide notice before your Personal Data is transferred and becomes subject to a different Privacy Policy.</li>
            <li><b>Disclosure for Law Enforcement: </b>Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</li>
            <li><b>Other Legal Requirements</b></li>
            <p>The company may disclose your personal data in the good faith belief that such action is necessary to :</p>
            <li>1. Comply with a legal obligation</li>
            <li>2. Protect and defend the rights or property of the company</li>
            <li>3. Prevent of investigable possible wrongdoing in connection with the service</li>
            <li>4. Protect the personal safety of users of the service or the public </li>
            <li>5. Protect against legal liability</li>
            </ul>
            </div>

            <div className="childrenPrivacy">
            <h2 >10. Children’s Privacy</h2>
            <p>Our service does not address anyone under the age of 18. We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your child has provided us with personal data, please contact us. If we become aware that we have collected personal data from anyone under the age of 18 without verification of parental consent, we take steps to remove that information from our servers.</p>
            <p>If we need to rely on consent as a legal basis for processing your information and your country requires consent from a parent, we may require your parent’s consent before we collect and use that information.</p>
            </div>

            <div className="links">
            <h2 >11. Links to Other Websites (Ads)</h2>
            <p>Our service may obtain links to other websites that are not operated by us. If you click on a third party link, you will be redirected to that third party’s site. We strongly advise you to review the privacy policy of every site you visit.</p>
            <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites of services.</p>
            </div>

            <div className="yourRights">
            <h2 >12. Your Rights Regarding the Personal Data You Provide to Us</h2>
            <p>If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please contact us.	</p>
            <p>In certain circumstances, you have the following data protection rights:</p>
            <ul>
            <li><b>The right to access, update or to delete </b>the information we have on you.</li>
            <li><b>The right of rectification. </b>You have the right to have your information rectified if that information is inaccurate or incomplete.</li>
            <li><b>The right to object. </b>You have the right to object to our processing of your Personal Data.</li>
            <li><b>The right of restriction. </b>You have the right to request that we restrict the processing of your personal information.</li>
            <li><b>The right to data portability. </b>You have the right to be provided with a copy of your Personal Data in a structured, machine-readable and commonly used format.</li>
            <li><b>The right to withdraw consent. </b>You also have the right to withdraw your consent at any time where DUNIYAA relied on your consent to process your personal information.</li>
            </ul>
            <p>NOTE: We may ask you to verify your identity before responding to such requests.</p>
            </div>

            <div className="disclosureText">
            <h2 >13. Disclosure Text for Inclusion in Privacy Policy</h2>
            <p>We may disclose to third party services certain personally identifiable information listed below:</p>
            <ul>
            <li>Information you provide us such as name, mobile number, email.</li>
            <li>Information we collect as you access and use our service, including device information, location, etc.</li>
            <p>This information is shared with third party service providers so that we can:</p>
            <li>Personalize the app for you.</li>
            <li>Perform behavioral analytics.</li>
            </ul>
            </div>

            <div className="anyUpdates">
            <h2 >14. Any Updates to this Privacy Policy</h2>
            <p>We will review and may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>
            <p>We will let you know via email and/or a prominent notice on our service, prior to the change becoming effective and update the ‘Last Modifies’ date at the top of this Privacy Policy.</p>
            <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
            </div>

            <div className="contacts">
            <h2 >15. Contact Us</h2>
            <p>If you have any questions about this Privacy Policy and our data policies, you can contact us:</p>
            <ul>
            <li>By visiting this page </li>
            <li>By email  </li>
            </ul>
            </div>
        </div>
        </>



    )
}

export default PrivacyAndPolicy;